---
title: Stackbit Fresh Theme
baseURL: "/"
params:
  layout_style: overflow
  palette: violet
  header:
    title: Stackbit Fresh
    tagline: Header Tagline
    profile_img: "/images/41825871.jpeg"
    bg: light
    has_nav: true
    has_social: true
  footer:
    content: "&copy; Ankesh Bharti. All rights reserved."
    links:
    - text: "Made with \U0001F496 in India"
      url: https://en.gravatar.com/shermisaurus
      new_window: true
disableKinds:
- RSS
