---
title: Ankesh Bharti's Weblog
baseURL: "/"
params:
  layout_style: overflow
  palette: violet
  header:
    title: Ankesh Bharti
    tagline: "@shermisaurus"
    profile_img: "/images/stand.jpeg"
    bg: light
    has_nav: true
    has_social: true
  footer:
    content: '&copy; Ankesh Bharti 2018-2019. All rights reserved. | <a href="https://madewithlove.org.in"
      target="_blank">Made with <span style="color: #e74c3c">&hearts;</span> in India</a>
      by Hugo | Forestry | Netlify | GitHub'
    links: []
disableKinds:
- RSS
disqusShortname: ankeshb
