---
title: Ankesh Bharti's Weblog
baseURL: "/"
params:
  layout_style: overflow
  palette: violet
  header:
    title: Ankesh Bharti
    tagline: "@shermisaurus"
    profile_img: "/images/stand.jpeg"
    bg: light
    has_nav: true
    has_social: true
  footer:
    content: "&copy; Ankesh Bharti 2018-2019. All rights reserved."
    links:
    - text: "| Made with \U0001F496 in India"
      url: https://madewithlove.org.in/
      new_window: true
disableKinds:
- RSS
